### ISSUE TITLE
In the manifest, how do you assert that sequel pro has been installed?

### ISSUE THREAD

**Issue by flyingbuddha** [boxen/puppet-sequel_pro#3]
I'd like to be able to check if the package has been installed successfully, but unsure how I do this.

Ordinarily I would do something like:

`require => Package['sequelpro']`

However, as the package is installed with a variable version number, the only check I believe I can do is:

`require => Class['sequel_pro']`

This wouldn't necessarily tell me when the package is installed, only that the class has been loaded.

Can you give me any advice please?

**Comment by todd** [comment]
Thanks for bringing this up, that's a good point. I'd entertain a pull request that strips the version from the Package name. Functionally, it should work the same without it and then you can subscribe to `Package['Sequel-Pro']`.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
